// vue-client/src/components/StepToTime.vue
<template>
  <div class="m2t">
    <h2>{{ title }}</h2>
    <!-- <NumberInput @change="calcResult" :val="stepUpper" />
    <NumberInput @change="calcResult" :val="stepLower" />
    <NumberInput @change="calcResult" :val="bpm" /> -->
    <h3>Result: {{ result.timeStr }}</h3>
  </div>
</template>

<script lang="ts">
import {
  Component,
  Prop,
  Vue,
  Emit,
} from 'vue-property-decorator';
import InputValue from '../models/input-value';
// import NumberInput from './NumberInput.vue';
import {
  stepToTime,
} from '../util';

@Component({
  components: {
    // NumberInput,
  },
})
export default class StepToTime extends Vue {
  @Prop() private title!: string;

  public stepUpper!: InputValue<number>;

  public stepLower!: InputValue<number>;

  public bpm!: InputValue<number>;

  private result = { time: 42, timeStr: 'unset' };

  created() {
    this.stepUpper = (new InputValue<number>())
      .setValue(1)
      .setLabel('');

    this.stepLower = (new InputValue<number>())
      .setValue(16)
      .setLabel('th at');

    this.bpm = (new InputValue<number>())
      .setValue(120)
      .setLabel('BPM');

    this.calcResult();
  }

  @Emit()
  private calcResult() {
    const time = stepToTime({
      step: this.stepUpper.value / this.stepLower.value,
      bpm: this.bpm.value,
    });
    const timeStr = `${time.toFixed(2)} ms`;
    this.result.time = time;
    this.result.timeStr = timeStr;
  }
}

</script>

<style scoped lang="less">
</style>

// ng-universal-client/src/app/step-to-time/step-to-time.component.ts
import { Component, OnInit } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

import { stepToTime } from '../util';

@Component({
  selector: 'app-step-to-time',
  templateUrl: './step-to-time.component.html',
  styleUrls: ['./step-to-time.component.scss', '../app.component.scss']
})
export class StepToTimeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }


  private _title!: string;
  get title() {
    return this._title;
  }

  public values = {
    stepUpper: "1",
    stepLower: "16",
    bpm: "120",
  }

  private _result = new BehaviorSubject({ time: 42, timeStr: 'unset' });
  get result() {
    return this._result.asObservable();
  }

  ngAfterContentChecked() {
    this.calcResult();
  }

  public calcResult() {
    const time = stepToTime({
      step: Number(this.values.stepUpper) / Number(this.values.stepLower),
      bpm: Number(this.values.bpm),
    });
    // const date = new Date(time);
    const timeStr = `${time.toFixed(2)} ms`;
    this._result.next({ time, timeStr });
  }
}

  <div class="container col p-100 m-8">
    <h2 class="w-100">Step To Time</h2>
    <app-number-input 
        class="w-100 m-8"
        (changed)="calcResult()" 
        [(value)]="values.stepUpper"
        [label]="''" 
    ></app-number-input>
    <app-number-input 
        class="w-100 m-8"
        (changed)="calcResult()" 
        [(value)]="values.stepLower"
        [label]="'th at'"
    ></app-number-input>
    <app-number-input 
        class="w-100 m-8"
        (changed)="calcResult()" 
        [(value)]="values.bpm"
        [label]="'bpm'"
    ></app-number-input>
        
    <h3 class="w-100 m-8">Result: {{ (result | async )?.timeStr }}</h3>
</div>
